model_name: fedformer
trainer_name: CSDI_trainer
config_path: 'conf/baseline/FEDformer_UTS.yaml'
root: './'
seed: 2024 # 随机数种子
# training
training_config:
  #exogenous_forecast 多推1
  seed: 2024 # 随机数种子
  des: 'test' # help='exp description'
  device: "cuda:3" # 训练或推理使用的GPU
  is_training: True # 'pred'还是'train'
  data: 'UTS_Dataset'
  # data_path: './datasets/ETTm1/data.pkl'
  features: M
  freq: 'h'
  checkpoints: './result/fedformer/'

  #task 
  # 此处暂未区分前向模型和后向模型的参数配置区别
  task_name: 'long_term_forecast'
  model_id: 'UTS_Dataset_96_96' 
  model_name: fedformer 
  #
  enc_in: 11
  dec_in: 11
  c_out: 11
  d_model: 512
  e_layers: 2
  d_layers: 1
  d_ff: 2048
  moving_avg: 25
  factor: 3
  n_heads: 8
  distil: True
  label_len: 0.5
  #forecasting task

  inverse: False
  seasonal_patterns: 'Monthly' #help='subset for M4

  #optimization
  num_workers: 10
  itr: 1
  train_epochs: 10
  batch_size: 96 # help='batch size of train input data'
  patience: 3 #help='early stopping patience'
  learning_rate: 0.001
  loss: 'MSE' #loss function
  lradj: 'type1' #help='adjust learning rate'
  use_amp: False #help='use automatic mixed precision training', default=False


  # de-stationary projector params
  p_hidden_dims: [128,128] #help='hidden layer dimensions of projector (List)')
  p_hidden_layers: 2

  # metrics (dtw)
  use_dtw: False #help='the controller of using dtw metric (dtw is time consuming, not suggested unless necessary)'

  # TimeXer
  patch_len: 16

  save_path: './experiments/fedformer/'
  model_path: '' # 如果不为空，则直接加载模型进行推理，否则进行训练



# data
data_config:
  is_non_stationary: False # 决定是否要进行非平稳时间序列的训练，1的话则进行归一化
  dataset_name: UTS_Dataset
  data_path: ./data/processed_data/1_datacenter.csv # 数据所在位置
  columns: ['cpu_util', 'gpu0_util', 'gpu1_util', 'gpu2_util',
       'gpu3_util', 'gpu4_util', 'gpu5_util', 'gpu6_util', 'gpu7_util',
       'memory', 'power'] # 确定取数据中哪些列及其相对位置
  target_cols: ['cpu_util', 'gpu0_util', 'gpu1_util', 'gpu2_util',
       'gpu3_util', 'gpu4_util', 'gpu5_util', 'gpu6_util', 'gpu7_util',
       'memory', 'power'] # 目标列名
  feature_cols_da: [] # 辅助变量，日前
  feature_cols_mask2D: [] # 辅助变量，日内
  feature_cols_mask1D: [] # 辅助变量，日内
  data_mode: 2 # 0的话就是使用数据长度切割数据，1的话就是使用时间切割数据
  unit_len: 12 # 一天的数据序列长度
  training_step: 1 # 训练时偏移的步长
  past_len: 10 # 历史窗长，多少个unit_len
  pred_len: 1 # 预测长度，多少个unit_len
  data_len: # data_mode为0
    end: "2024-11-19 23:45:00" # 确定数据集的终止时间
    train: 366 # 训练集长度，多少个unit_len，-1时为剩余的全部数据
    valid: 32 # 验证集长度，多少个unit_len
    test: 62 # 测试集长度，多少个unit_len
    shift: 0 # 相较于数据末尾的向前偏移量，多少个unit_len
  data_time: # data_mode为1
    train: # 训练集
      start: "2025-07-29 09:42:00"
      end: "2025-08-19 09:21:30"
    valid: # 验证集
      start: "2025-08-19 09:22:00"
      end: "2025-08-22 09:21:30"
    test: # 测试集
      start: "2025-08-22 09:22:00"
      end: "2025-08-28 09:16:30"
  train_val_test_ratio: [0.7, 0.1, 0.2] #data_mode为2

# model
model_config:
  model: FEDformer

  dropout: 0.1
  embed: 'timeF'
  activation: 'gelu'
  output_attention: False
  channel_independence: 1 #help='0: channel dependence 1: channel independence for FreTS model'
  decomp_method: 'moving_avg' #help='method of series decompsition, only support moving_avg or dft_decomp')
  use_norm: 1 #help='whether to use normalize; True 1 False 0'
  down_sampling_layers: 0   #help='whether to use normalize; True 1 False 0'
  down_sampling_window: 1   #help='num of down sampling layers'
  dowm_sampling_method: None #help='down sampling method, only support avg, max, conv'
  seg_len: 48


  #augmentation_ratio
  augmentation_ratio: 0  # How many times to augment
  jitter: false  # Jitter preset augmentation
  scaling: false  # Scaling preset augmentation
  permutation: false  # Equal Length Permutation preset augmentation
  randompermutation: false  # Random Length Permutation preset augmentation
  magwarp: false  # Magnitude warp preset augmentation
  timewarp: false  # Time warp preset augmentation
  windowslice: false  # Window slice preset augmentation
  windowwarp: false  # Window warp preset augmentation
  rotation: false  # Rotation preset augmentation
  spawner: false  # SPAWNER preset augmentation
  dtwwarp: false  # DTW warp preset augmentation
  shapedtwwarp: false  # Shape DTW warp preset augmentation
  wdba: false  # Weighted DBA preset augmentation
  discdtw: false  # Discriminative DTW warp preset augmentation
  discsdtw: false  # Discriminative shape DTW warp preset augmentation
  extra_tag: ""  # Anything extra