# data
data_path: data/processed_data/1_datacenter.csv
train_val_test_ratio: [0.7, 0.1, 0.2]

# Training
dataset_name: UTS_Dataset
model_name: nbeats
trainer_name: UTS_trainer
loss_name: MAE
use_gpu: True
use_multi_gpu: False
devices: '0'
gpu: 0
seed: 9432
patience: 5
learning_rate: 0.001
pct_start: 0.2
epochs: 100
batch_size: 64

in_len: 12
out_len: 12
stride: 1
norm_type: "ZScore"
if_col_norm: True
is_norm_loss: True
timeenc: 0
freq: '30s'

# model
type: "generic"
input_size: 12
output_size: 12
stacks: 10
layers: 3
layer_size: 128

dropout: 0.3
T_embed_dim: 8 # 4(feats)*8=32

early_stoping: True
skip_epoch: 1
save_results: True